language: python
python:
  - 2.6
  - 2.7
  - pypy
  - 3.2
  - 3.3
  - 3.4
  - nightly
  - pypy3

notifications:
  email: false
 
# Install packages
install:
  - travis_retry pip install coveralls
  - travis_retry python setup.py install
 
# Run test
script:
  - nosetests --verbose --with-coverage --cover-branches --cover-package=usfm2osis --logging-level=INFO
 
# Calculate coverage
after_success:
  - coveralls --verbose --rcfile=.coveragerc
